// Copyright 2023 Danny Nguyen (danny@keeb.io)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define SPLIT_HAND_PIN GP4
#define USB_VBUS_PIN GP0
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13
#define SERIAL_USART_PIN_SWAP
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define I2C_DRIVER I2CD2
#define I2C1_SDA_PIN GP10
#define I2C1_SCL_PIN GP11

/* personal */
#define MOUSEKEY_INTERVAL       16
#define MOUSEKEY_DELAY          100
#define MOUSEKEY_TIME_TO_MAX    64
#define MOUSEKEY_MAX_SPEED      6
#define MOUSEKEY_WHEEL_DELAY 30
#define TAPPING_TERM    150
#define QUICK_TAP_TERM 0